### ISSUE TITLE
Calling 'metadata.reflect(bind=connection)' probably creates new connection to database (it takes about 5 seconds when executed against AWS based database)

### ISSUE THREAD

**Issue by JakubBraz** [KajaBraz/ChatBox#36]

**Comment by JakubBraz** [comment]
![obraz](https://user-images.githubusercontent.com/3051330/116302518-90739800-a7a1-11eb-9697-9c6b514ca459.png)

**Comment by JakubBraz** [comment]
raw 'connect' also takes about 4-5 seconds, that is ok, but that is why this `metadata.bind...` probably creates new connection

![obraz](https://user-images.githubusercontent.com/3051330/116302732-d597ca00-a7a1-11eb-9928-af793fd3edff.png)

**Comment by KajaBraz** [comment]
database handling has been remodelled from separate functions into class; creating the connection and calling of metadata.reflect are now executed only once (in the constructor)
