### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by KajaBraz** [KajaBraz/ChatBox#4]

**Comment by KajaBraz** [comment]
v. 0
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/368d61b7-f2a7-407f-858a-f913ccae42c6)

**Comment by KajaBraz** [comment]
v. 1
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/c6e71bfa-60d4-446f-afbb-6eeee21df9b3)

**Comment by KajaBraz** [comment]
v. 2
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/df9843eb-7520-42f5-a2e5-932849eb15d4)

**Comment by KajaBraz** [comment]
v. 3
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/2ba989fb-40dd-435e-ac0c-5ca98225f7a0) 

Display placeholders when login or chat name is not provided:
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/5d0d0df6-50ff-4145-b979-61f7d97d1cad)

**Comment by KajaBraz** [comment]
v. 4 https://colorhunt.co/palette/b3ffaef8ffdbff6464ff7d7d
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/436a0298-500f-46fa-984e-639681bcccfe)

v. 5 https://colorhunt.co/palette/222831393e46ffd369eeeeee
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/d75aa63a-9b63-4e79-995a-a3163649b225)

v. 6 rgb(249, 199, 79) + rgb(39, 125, 161)
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/111ae518-21bf-455f-b989-91e62e5a1bae)

v. 7 #4682A9 + #91C8E4
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/5ca95c13-cc60-43c5-8415-e5fd3fcd101b)

v. 8 #FFCB74 + #EA907A + #F4F6FF
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/d4aa3f6c-e235-4f78-8c27-6a4441165777)

**Comment by KajaBraz** [comment]
v. 9 https://colorhunt.co/palette/fbfad3c6e377729d3936622b
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/34c8ec40-6a0f-4dcf-b2bd-6d659c50a11a)

v. 10 https://colorhunt.co/palette/fbfad3c6e377729d3936622b
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/09b5df93-cebf-4d33-8f1c-c77ed5a77cb8)

v. 11 https://colorhunt.co/palette/fcecddffc288fea82fff6701
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/9becb8ab-59ae-41be-880a-48b943fb7d6b)

v. 12 https://colorhunt.co/palette/3c625561876ea6bb8deae7b1
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/2cff5a7e-7301-494d-bd33-0ef8cdaea115)

v. 13 https://colorhunt.co/palette/feffdeddffbc91c78852734d
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/1a44d3bf-7ff9-4f86-b974-522dcd404319)

v. 14 https://colorhunt.co/palette/feffdeddffbc91c78852734d
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/d6049fd9-4848-457b-9470-86db2a062268)

v. 15 https://colorhunt.co/palette/2c33332e4f4f0e8388cbe4de
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/9050ce96-afa6-48de-8160-4483f6940ac3)

v. 16
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/7ea991f0-ed93-4b06-9933-5bde24ed6d2d)

**Comment by KajaBraz** [comment]
v. 17
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/fc32b9f2-1317-4884-bf92-23893acec8cb)

v. 18 https://colorhunt.co/palette/f4f4f2e8e8e8bbbfca495464
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/401790c2-ba10-4791-ad4a-4407b33b84a0)

v. 19
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/cd230c60-9b46-48bd-bb52-5a2030b60d6b)

v. 20 https://colorhunt.co/palette/fffffff9f6f7ffe8d6ff971d
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/36b86828-93cb-4563-a6ca-a93ba4ddce59)

v. 21 https://colorhunt.co/palette/faf6e9ece8d9fffdf6494949
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/77ceb7ce-5ca8-4c9c-9de2-a640ac552a6e)

v. 22 https://colorhunt.co/palette/f9f9f9ded5c4ef7e56305973 (modified)
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/a2b27b75-5c40-403a-92a0-18a017cdfb85)

v. 23 https://colorhunt.co/palette/ccd6a6dae2b6dfe8ccf7eddb
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/c0706a76-4808-40f6-ac96-ca884fc27152)

v. 24 https://colorhunt.co/palette/14182921294cf2dea8f9f2d7 (modified)
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/cd33168c-2fc5-417e-9580-c557ecd95357)

v. 25 https://coolors.co/f0e5d3-f0e5ca-dfd5a5
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/ccb8af2d-79e4-40b6-98d5-298a945632cd)

**Comment by KajaBraz** [comment]
It is how it looks like with shades (pic. for v. 21)
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/056f3b85-81cb-464c-ac03-4071510c925c)

**Comment by KajaBraz** [comment]
v. 26
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/9816a214-b5e3-4dad-a647-bd264f2c80ee)

v. 27 https://coolors.co/2d2d2a-e5d352-d9e76c-353831-38423b
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/25ce53ab-e1a8-44ee-b69c-300674cdabfb)

v. 28 https://coolors.co/f98948-e5d352-5d3a00-684e32-7b9ea8 (modified)
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/ddd18869-c5a0-4a57-8075-aeec3f8f2937)

v. 29 https://coolors.co/323031-f5f3bb-3d3b3c-5f5b6b-f08a4b
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/668f4bc3-35cf-4712-8adb-6505200e634b)

v. 30 https://coolors.co/60594d-f5f3bb-95afba-af9bb6-f08a4b
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/93ce50b6-4dfb-4377-aa3c-c715bf51f299)

v. 31
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/15566ff1-b79e-4858-bc3f-609cf2f490c1)

v. 32
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/fc94f1e4-a40b-477f-858f-f618b71b4d73)

**Comment by KajaBraz** [comment]
Some of the previous versions updated

v. 4
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/10d3d3a5-c8a0-4f7e-b2b0-b4ddb361ee9b)

v. 14.1
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/bb5b6e8e-9251-4bda-9fa2-91e73df8ed91)

v. 27
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/70df2531-10b6-47ce-898c-83b6a3c02a6b)

v. 28.1
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/edc78ad4-294f-487c-8031-ba33a3638ce4)

v. 29
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/ff942bdf-5c7a-4526-af4e-c19b39c99a39)
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/7521d11b-7ab2-42cb-9f35-9382677d3c33)

v. 30.1
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/a84b0480-3061-482c-bb56-478f4da6ae39)

v. 31.1
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/84bf5fa3-ef5d-4585-9f34-507a0d6faf81)

v. 32.1
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/82727a00-056d-46ec-862a-0ca77681041a)

v. 33
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/d27e109f-66b1-4e02-ada5-4f713051cbdb)

v. 34
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/441c9ac8-8b7a-4a2b-9f27-8ac2267f9652)

v. 35
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/a932369b-fb98-4316-a6e2-0ac84f4d3a35)

**Comment by KajaBraz** [comment]
v. 36 https://colorhunt.co/palette/025464e57c23e8aa42f8f1f1
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/3599b601-4b03-4663-aed5-298f08ca63b4)

v. 37 https://colorhunt.co/palette/015668263f44ffd369fff1cf
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/3fcd2935-c367-4e5e-84b3-e203895b4c6c)

v. 38 https://coolors.co/0d3b66-faf0ca-f4d35e-ee964b-f95738 (Naples yellow!)
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/83ceda3e-afe9-40f7-a47e-dc29927925ff)

v. 39 https://coolors.co/292f36-4ecdc4-f7fff7-ff6b6b-ffe66d (Naples yellow!)
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/a3606737-ae05-4257-a2af-5c6ac25fcba5)

v. 40 https://coolors.co/011638-f7fff7-364156-214e34-ffe66d (Naples yellow!)
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/7257607d-9ad0-499e-821f-86dbdae0cce0)

**Comment by KajaBraz** [comment]
Yellow options
https://coolors.co/e8aa42-ffd369-f4d35e-ffe66d

**Comment by KajaBraz** [comment]
v. 41.1 https://coolors.co/141414-1985a1-ffe66d-f4f3ee-c9f0ff
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/a5593113-1d73-41f2-a8fe-1802c8440794)

v. 41.2
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/f0c4477a-e15a-491d-8606-ea6841985790)

v. 42
![obraz](https://github.com/KajaBraz/ChatBox/assets/58611238/cfc737cb-164f-4713-b020-2052f893e2db)

**Comment by JakubBraz** [comment]
The best is v. 5.2, second the best v. 42, IMO
